services:
  - type: web
    name: medexplain
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: medexplain-db
          property: connectionString

databases:
  - name: medexplain-db
    plan: free
